model:
  representation_size: 8
  encoder:
    input_channels: 3
  decoder:
    output_channels: 3
trainer:
  dataset_path: 'vsg'
  batch_size: 512
  epochs: 50
  optimizer:
    learning_rate: 1e-4
    weight_decay: 0.0