model:
  representation_size: 8,
  encoder:
    input_shape: 625,
  decoder:
    output_shape: 625,

trainer:
  dataset_path: '',
  batch_size: 512,
  epochs: 50,
  optimizer:
    learning_rate: 1e-4,
    weight_decay: 0.0,