model:
  representation_size: 8
  encoder:
    input_shape: 625
  decoder:
    output_shape: 625
trainer:
  dataset_path: './vae_dataset/**/*.png'
  img_size:
    x: 64
    y: 64
  batch_size: 512
  epochs: 50
  gpu: 1
  optimizer:
    learning_rate: 1e-4
    weight_decay: 0.0